pool:
  vmImage: ubuntu-latest

steps:

- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: 'acr-team1'
  displayName: set ACR secret on cluster

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    manifests: 'k8s/'
    rolloutStatusTimeout: '12'
  displayName: initialize cluster
