pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: 'acr-team1'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-team1-config-dev'
    namespace: 'team1'
    command: 'delete'
    arguments: '-f .'
    workingDirectory: './k8s'
    outputFormat: 'yaml'
  displayName: clear previous items

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'k8s-team1-config-dev'
    namespace: 'team1'
    command: 'apply'
    arguments: '-f .'
    workingDirectory: './k8s'
    outputFormat: 'yaml'
  displayName: deploy new manifests