pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: 'RevatureProject3May24DevOpsContainersACR'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    strategy: 'canary'
    percentage: '10'
    manifests: './k8s'
    imagePullSecrets: 'acrSecret'
    rolloutStatusTimeout: '300'