resources:
  repositories:
  - repository: manifests
    type: github
    endpoint: Team1-Project3
    name: 1053-August-Duet-Project-Registry/project-registry-devops
    ref: refs/heads/feature-helm

pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: 'RevatureProject3May24DevOpsContainersACR'

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    strategy: 'canary'
    percentage: '10'
    manifests: './k8s@manifests'
    imagePullSecrets: 'acrSecret'
    rolloutStatusTimeout: '300'