pool:
  vmImage: ubuntu-latest
variables:
  containerServiceConnection: 'acr-team1'
  k8sServiceConnection: 'k8s-team1-config-dev'
  namespace: 'team1'
  prereqManifestPath: 'k8s/prerequisites/*'
  microserviceManifestPath: 'k8s/microservices/*'
steps:

- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: ${{ variables.k8sServiceConnection }}
    namespace: ${{ variables.namespace }}
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: ${{ variables.containerServiceConnection }}
  displayName: set imagePullSecret on cluster

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: ${{ variables.k8sServiceConnection }}
    namespace: ${{ variables.namespace }}
    manifests: ${{ variables.prereqManifestPath }}
  displayName: initialize cluster prerequisites

- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: ${{ variables.k8sServiceConnection }}
    namespace: ${{ variables.namespace }}
    manifests: ${{ variables.microserviceManifestPath }}
  displayName: initialize cluster microservices