pool:
  vmImage: ubuntu-latest

steps:
- task: KubernetesManifest@0
  inputs:
    action: 'createSecret'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    secretType: 'dockerRegistry'
    secretName: 'acr-secret'
    dockerRegistryEndpoint: 'RevatureProject3May24DevOpsContainersACR'
  displayName: set ACR secret on cluster

- task: KubernetesManifest@0
  inputs:
    action: 'delete'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    arguments: '-f ./k8s/'
  displayName: clear AKS dev cluster


- task: KubernetesManifest@0
  inputs:
    action: 'deploy'
    kubernetesServiceConnection: 'k8s-team1-config-dev'
    namespace: 'team1'
    manifests: 'k8s/account.yaml'
    containers: 'may24DevOpsContainers.azurecr.io/project-registry-account-microservice:0.0.1-SNAPSHOT'
    imagePullSecrets: 'acr-secret'
    rolloutStatusTimeout: '1200'
  displayName: deploy to AKS dev cluster