apiVersion: apps/v1
kind: Deployment
metadata:
  name: account
spec:
  selector:
    matchLabels:
      app: account
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - name: account
        image: 'danielhine/project-registry-account:latest'
        resources:
          limits:
            memory: "512Mi"
            cpu: "125m"
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: SPRING_CLOUD_CONSUL_HOST
        - name: SPRING_APPLICATION_NAME
          value: account-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: account
spec:
  type: NodePort
  selector:
    app: account
  ports:
  - port: 8081
    targetPort: 8081

