apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: 'danielhine/project-registry-gateway:latest'
        resources:
          requests:
            memory: "1024Mi"
            cpu: "750m"
          limits:
            memory: "1024Mi"
            cpu: "750m"
        ports:
        - containerPort: 8085
        env:
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: SPRING_CLOUD_CONSUL_HOST

---

apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8085
    targetPort: 8085


