apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  selector:
    matchLabels:
      app: tracking
  template:
    metadata:
      labels:
        app: tracking
    spec:
      containers:
      - name: tracking
        image: 'danielhine/project-registry-tracking:latest'
        resources:
          requests:
            memory: "712Mi"
            cpu: "250m"
          limits:
            memory: "712Mi"
            cpu: "250m"
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_CLOUD_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: project-configmap
              key: SPRING_CLOUD_CONSUL_HOST
        - name: SPRING_APPLICATION_NAME
          value: tracking-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: tracking
spec:
  type: NodePort
  selector:
    app: tracking
  ports:
  - port: 8083
    targetPort: 8083

